<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>RFQ Reminder</title>
</head>
<body style="font-family: Arial, sans-serif; background-color: #f5f6fa; padding: 30px;">

    <div style="background-color: #ffffff; padding: 20px 30px; border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,0.1);">
        <h2 style="color: #2c3e50;">⏰ RFQ Reminder: {{ $rfq->rfq_code }}</h2>

        <p style="color: #555;">
            Hello Admin,<br><br>
            This is a friendly reminder that the following RFQ has been pending for more than <strong>24 hours</strong> without response:
        </p>

        <table style="width:100%; border-collapse: collapse; margin: 20px 0;">
            <tr>
                <td style="padding: 8px; border: 1px solid #eee;"><strong>RFQ Code</strong></td>
                <td style="padding: 8px; border: 1px solid #eee;">{{ $rfq->rfq_code }}</td>
            </tr>
            <tr>
                <td style="padding: 8px; border: 1px solid #eee;"><strong>Customer Name</strong></td>
                <td style="padding: 8px; border: 1px solid #eee;">{{ $rfq->name }}</td>
            </tr>
            <tr>
                <td style="padding: 8px; border: 1px solid #eee;"><strong>Email</strong></td>
                <td style="padding: 8px; border: 1px solid #eee;">{{ $rfq->email }}</td>
            </tr>
            <tr>
                <td style="padding: 8px; border: 1px solid #eee;"><strong>Submitted On</strong></td>
                <td style="padding: 8px; border: 1px solid #eee;">{{ $rfq->created_at->format('d M Y, h:i A') }}</td>
            </tr>
        </table>

        <p style="color: #555;">
            Please review and respond to this RFQ at your earliest convenience.
        </p>

        <a href="{{ url('/admin/rfqs/' . $rfq->id) }}"
           style="display: inline-block; padding: 10px 20px; background-color: #2ecc71; color: white; text-decoration: none; border-radius: 5px;">
            View RFQ
        </a>

        <p style="margin-top: 20px; color: #888; font-size: 12px;">
            This is an automated reminder generated by the system.
        </p>
    </div>

</body>
</html>
